### ISSUE TITLE
Disable experimental feature

### ISSUE THREAD

**Issue by kaelspencer** [jeymichael/vscodelogcat#1]
Hi! Is it possible to add some plugin settings to disable the experimental feature which disables editing? It makes it tough to have a file open that you want to edit next to a file using this plugin. 

Any chance you could add the source here? I'd be interested in looking at it and seeing if I could add anything.

**Comment by jeymichael** [comment]
@kaelspencer  The edit is just not a strong constraint.  I believe if you do tab, or select text and delete, copy, paste etc, it will let you edit.  
I know, a setting to turn it off/on would be useful.  (Out of town for a few weeks, not in front of my PC)

**Comment by kaelspencer** [comment]
Tab, delete, copy + paste do affect the document but it doesn't allow me to edit like normal. This effects all files in that VSCode window, so if I open a logcat file with other things, I have to close the window and reopen it in order to edit.

**Comment by murder** [comment]
I'm here also writing due to that 
The logcatplusplus.readOnlyFile setting does NOT work - I tried setting to FALSE no lucky

And the extension is very good - besides that

**Comment by ChronSyn** [comment]
The `logcatplusplus.readOnlyFile` setting logic absolutely needs fixing.

It's an incredible extension, but it's extremely disruptive and frustrating when trying to debug, and being unable to edit any open file because of the extension.

Reloading the window might only take a moment, but if I have to entirely close the logcat file, which means I can no longer reference the logs while trying to hunt down an issue while debugging. It actively makes debugging more difficult because of this bug.

**Comment by Albinoman887** [comment]
I fixed the readonly setting not working... i'll fork and upload

**Comment by Albinoman887** [comment]
https://github.com/jeymichael/vscodelogcat/pull/3

**Comment by jeymichael** [comment]
Fixed the code to honor the readonly flag, and turned the flag to OFF by default.  
Deployed ver 0.0.5    Please test and confirm here.

**Comment by jeymichael** [comment]
Closing. Fix deployed in ver 0.0.5
